'use client';

import React, { useState, useEffect } from 'react';
import AdminLayout from '@/components/layout/AdminLayout';
import { AIMetrics, SentimentAnalysis } from '@/types';
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ResponsiveContainer,
} from 'recharts';

export default function AIMonitoringPage() {
  const [metrics, setMetrics] = useState<AIMetrics | null>(null);
  const [sentimentData, setSentimentData] = useState<SentimentAnalysis[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [retrainingInProgress, setRetrainingInProgress] = useState(false);

  useEffect(() => {
    fetchAIMetrics();
  }, []);

  const fetchAIMetrics = async () => {
    try {
      setLoading(true);
      // TODO: Replace with actual API call
      const mockMetrics: AIMetrics = {
        totalRecommendations: 15420,
        averageResponseTime: 1.2,
        clickThroughRate: 32.5,
        totalConversations: 8950,
        averageConversationLength: 4.3,
        userSatisfactionRating: 4.6,
      };

      const mockSentimentData: SentimentAnalysis[] = [
        {
          hotelId: '1',
          hotelName: 'Luxury Hotel Phnom Penh',
          positiveCount: 245,
          neutralCount: 89,
          negativeCount: 12,
          averageSentiment: 0.85,
        },
        {
          hotelId: '2',
          hotelName: 'Riverside Resort',
          positiveCount: 312,
          neutralCount: 102,
          negativeCount: 18,
          averageSentiment: 0.82,
        },
      ];

      setMetrics(mockMetrics);
      setSentimentData(mockSentimentData);
    } catch (err) {
      console.error('Error fetching AI metrics:', err);
      setError('Failed to load AI metrics');
    } finally {
      setLoading(false);
    }
  };

  const handleRetrain = async () => {
    try {
      setRetrainingInProgress(true);
      // TODO: Call API to trigger retraining
      alert('AI model retraining started. This may take several minutes.');
      setRetrainingInProgress(false);
    } catch (err) {
      console.error('Error triggering retraining:', err);
      setError('Failed to trigger retraining');
      setRetrainingInProgress(false);
    }
  };

  if (loading) {
    return (
      <AdminLayout>
        <div className="flex items-center justify-center h-full">
          <p className="text-gray-600">Loading AI metrics...</p>
        </div>
      </AdminLayout>
    );
  }

  const sentimentChartData = sentimentData.map((s) => ({
    name: s.hotelName,
    positive: s.positiveCount,
    neutral: s.neutralCount,
    negative: s.negativeCount,
  }));

  return (
    <AdminLayout>
      <div>
        <div className="flex justify-between items-center mb-8">
          <h1 className="text-3xl font-bold text-gray-900">AI System Monitoring</h1>
          <button
            onClick={handleRetrain}
            disabled={retrainingInProgress}
            className="px-6 py-2 bg-blue-600 text-white rounded-lg font-semibold hover:bg-blue-700 disabled:bg-gray-400"
          >
            {retrainingInProgress ? 'Retraining...' : '🔄 Retrain Model'}
          </button>
        </div>

        {error && (
          <div className="bg-red-50 border border-red-200 rounded-lg p-4 mb-6 text-red-700">
            {error}
          </div>
        )}

        {metrics && (
          <>
            {/* AI Metrics Cards */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
              <div className="bg-white rounded-lg shadow p-6">
                <p className="text-gray-600 text-sm font-medium mb-2">Total Recommendations</p>
                <p className="text-3xl font-bold text-gray-900">{metrics.totalRecommendations.toLocaleString()}</p>
                <p className="text-xs text-gray-500 mt-2">Generated by AI engine</p>
              </div>

              <div className="bg-white rounded-lg shadow p-6">
                <p className="text-gray-600 text-sm font-medium mb-2">Avg Response Time</p>
                <p className="text-3xl font-bold text-gray-900">{metrics.averageResponseTime}s</p>
                <p className="text-xs text-gray-500 mt-2">Per recommendation</p>
              </div>

              <div className="bg-white rounded-lg shadow p-6">
                <p className="text-gray-600 text-sm font-medium mb-2">Click-Through Rate</p>
                <p className="text-3xl font-bold text-gray-900">{metrics.clickThroughRate}%</p>
                <p className="text-xs text-gray-500 mt-2">User engagement</p>
              </div>
            </div>

            {/* Chat Assistant Metrics */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
              <div className="bg-white rounded-lg shadow p-6">
                <p className="text-gray-600 text-sm font-medium mb-2">Total Conversations</p>
                <p className="text-3xl font-bold text-gray-900">{metrics.totalConversations.toLocaleString()}</p>
                <p className="text-xs text-gray-500 mt-2">Chat sessions</p>
              </div>

              <div className="bg-white rounded-lg shadow p-6">
                <p className="text-gray-600 text-sm font-medium mb-2">Avg Conversation Length</p>
                <p className="text-3xl font-bold text-gray-900">{metrics.averageConversationLength}</p>
                <p className="text-xs text-gray-500 mt-2">Messages per session</p>
              </div>

              <div className="bg-white rounded-lg shadow p-6">
                <p className="text-gray-600 text-sm font-medium mb-2">User Satisfaction</p>
                <p className="text-3xl font-bold text-gray-900">⭐ {metrics.userSatisfactionRating}</p>
                <p className="text-xs text-gray-500 mt-2">Out of 5.0</p>
              </div>
            </div>

            {/* Sentiment Analysis Chart */}
            <div className="bg-white rounded-lg shadow p-6 mb-8">
              <h2 className="text-xl font-bold text-gray-900 mb-4">Sentiment Analysis by Hotel</h2>
              <ResponsiveContainer width="100%" height={300}>
                <BarChart data={sentimentChartData}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis dataKey="name" />
                  <YAxis />
                  <Tooltip />
                  <Legend />
                  <Bar dataKey="positive" fill="#10b981" name="Positive" />
                  <Bar dataKey="neutral" fill="#f59e0b" name="Neutral" />
                  <Bar dataKey="negative" fill="#ef4444" name="Negative" />
                </BarChart>
              </ResponsiveContainer>
            </div>

            {/* Sentiment Details Table */}
            <div className="bg-white rounded-lg shadow overflow-hidden">
              <div className="p-6 border-b border-gray-200">
                <h2 className="text-xl font-bold text-gray-900">Sentiment Details</h2>
              </div>
              <div className="overflow-x-auto">
                <table className="w-full">
                  <thead className="bg-gray-50 border-b border-gray-200">
                    <tr>
                      <th className="px-6 py-3 text-left text-sm font-semibold text-gray-700">Hotel</th>
                      <th className="px-6 py-3 text-left text-sm font-semibold text-gray-700">Positive</th>
                      <th className="px-6 py-3 text-left text-sm font-semibold text-gray-700">Neutral</th>
                      <th className="px-6 py-3 text-left text-sm font-semibold text-gray-700">Negative</th>
                      <th className="px-6 py-3 text-left text-sm font-semibold text-gray-700">Avg Sentiment</th>
                    </tr>
                  </thead>
                  <tbody>
                    {sentimentData.map((sentiment) => (
                      <tr key={sentiment.hotelId} className="border-b border-gray-200 hover:bg-gray-50">
                        <td className="px-6 py-4 font-semibold text-gray-900">{sentiment.hotelName}</td>
                        <td className="px-6 py-4 text-green-600 font-semibold">{sentiment.positiveCount}</td>
                        <td className="px-6 py-4 text-yellow-600 font-semibold">{sentiment.neutralCount}</td>
                        <td className="px-6 py-4 text-red-600 font-semibold">{sentiment.negativeCount}</td>
                        <td className="px-6 py-4">
                          <div className="flex items-center gap-2">
                            <div className="w-24 bg-gray-200 rounded-full h-2">
                              <div
                                className="bg-green-500 h-2 rounded-full"
                                style={{ width: `${sentiment.averageSentiment * 100}%` }}
                              ></div>
                            </div>
                            <span className="text-gray-700 font-semibold">{(sentiment.averageSentiment * 100).toFixed(0)}%</span>
                          </div>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          </>
        )}
      </div>
    </AdminLayout>
  );
}

